### PR TITLE
Junit For Edit parser and Some Bug Fixing Of Edit

### LINKED ISSUE #148: Do a simple check on the edit parameters hashset on whether its empty
ss1

Right now it doesnt look as nice

### LINKED ISSUE #169: [PE-D] UG 2.1.3: Parameter Return in add etf
This is a very minor thing, but the name for the "Returns" parameter does not match with the name in the given example usage ("Past Returns").

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: BryanElmer/ped#4

### LINKED ISSUE #178: [PE-D] No chance given to user when he messes up his edit inputs. Perhaps allow user one more chance?
-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ThaddeusLim99/ped#5

### LINKED ISSUE #179: [PE-D] Editing the remarks of an instrument.
---
Type: Stock     [ ]  
Name: xD  
Current Price: 1.0  
Sentiment: positive  
Remarks:  
---
mTracker$> edit 16  
        Please enter one or more Stock parameters to edit.
        name, current-price, sentiment, remark  
mTracker$> remarks  
remarks is an invalid attribute of this instrument and will be ignored.
---

In this figure above, in the viewing command, the remarks parameter is names as "remarks", however in the edit command it is names as "remark".  
(May cause confusion to users, maybe can make it the same in both commands.)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: BryanElmer/ped#7

### LINKED ISSUE #193: [PE-D] Unnecessary Before and Changed to when user does not change anything
It is unnecessary to print out the before and changed to when nothing is changed by user

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LouisLouis19/ped#8

### PR DESCRIPTION
**Pull request by kum-wh**
Implements #137 
Implements #150 
Bugs:
Fixes #148 
Fixes #169 
Fixes #178
Fixes #179
Fixes #193

### CODE REVIEW

File: src/test/java/seedu/mtracker/console/EditParserTest.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+
+    String formatConsoleInput(String input) {
+        return String.format(input, System.lineSeparator());
+    }
+
+    void simulateConsoleInput(String input) {
+        String formattedInput = formatConsoleInput(input);
+        ByteArrayInputStream inputStreamBytes = new ByteArrayInputStream(formattedInput.getBytes());
+        System.setIn(inputStreamBytes);
+    }
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditParserTest.java:50]: I think can get this method to inherit from the AddInstrumentParserTest. But rename the AddInstrumentParserTest to like GeneralInstrumentParserTest or InstrumentParserTest. Cause your edit class test is not exactly addparser

File: src/test/java/seedu/mtracker/console/EditParserTest.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+    HashMap<String,String> initialiseTestResources(String[] expectedKeys, String[] expectedValues) {
+        HashMap<String,String> expectedResult = new HashMap<>();
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditParserTest.java:53]:
```suggestion
        HashMap<String, String> expectedResult = new HashMap<>();
```

Can remove the space, check it carefully for the rest of the code

File: src/test/java/seedu/mtracker/console/EditParserTest.java [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+        }
+        return expectedResult;
+    }
+
+    void testEditInstrumentParameters(String input, HashSet<String> expectedParameters,
+                                      String[] expectedKeys, String[] expectedValues) {
+        simulateConsoleInput(input);
+        HashMap<String,String> expectedHash = initialiseTestResources(expectedKeys, expectedValues);
+        EditInstrumentParser editInstrumentParser = new EditInstrumentParser();
+        editInstrumentParser.getParametersToEdit(expectedParameters, TEST_STOCK, TEST_INDEX);
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditParserTest.java:65]: Sry I didnt catch this earlier. The getParametersToEdit method has an exact name as the one in the inputParser which confused me. Can rename the "getParametersToEdit" method to like "createEditCommand"

File: src/test/java/seedu/mtracker/console/EditParserTest.java [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+import seedu.mtracker.model.subinstrument.Stock;
+
+import java.io.ByteArrayInputStream;
+import java.util.Arrays;
+import java.util.HashMap;
+import java.util.HashSet;
+
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+public class EditParserTest {
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditParserTest.java:14]: Why is this not EditInstrumentParserTest

File: src/test/java/seedu/mtracker/console/EditParserTest.java [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+
+    public static final String SEPARATOR_SPECIFIER = "%1$s";
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditParserTest.java:16]: Remove when you extend this class

**Review by theodorekwok — COMMENTED** [review]
Good work, just some comments

File: src/test/java/seedu/mtracker/console/EditParserTest.java (hunk 1 above)
Comment (kum-wh) [reply src/test/java/seedu/mtracker/console/EditParserTest.java:50]: oh i never notice that those function have been abstracted out

File: src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+    public static final Instrument TEST_STOCK = new Stock(TEST_NAME, TEST_PRICE, TEST_SENTIMENT, TEST_REMARK);
+    public static final int TEST_INDEX = 0;
+
+    @Override
+    public int getParameterSize() {
+        return 0;
+    }
+
+    HashMap<String,String> initialiseTestResources(String[] expectedKeys, String[] expectedValues) {
+        HashMap<String, String> expectedResult = new HashMap<>();
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java:45]: Can add an assert here that length of expectedKeys == length of expectedValues

**Review by theodorekwok — COMMENTED** [review]
Good work just some minor comments and can merge

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java [hunk 7]
```diff
@@ -116,13 +117,20 @@ public static void editExpiryParameter(HashSet<String> parametersGiven) {
...
+            inputExpiry = getUserInput(WORKSPACE);
         }
         editedParameters.put(EXPIRY_ATTRIBUTE, inputExpiry);
     }
 
+    public static void editDoneStatus(HashSet<String> parametersGiven) {
+        if (!parametersGiven.contains(DONE_ATTRIBUTE)) {
+            return;
+        }
+        editedParameters.put(DONE_ATTRIBUTE,DONE_ATTRIBUTE);
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/EditInstrumentParser.java:131]:
```suggestion
        editedParameters.put(DONE_ATTRIBUTE, DONE_ATTRIBUTE);
```

Can get the user input like put in yes/no to set it as done or undone. The editing of status can go both ways

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java [hunk 8]
```diff
@@ -16,11 +16,12 @@
...
     protected static final String CURRENT_PRICE_ATTRIBUTE = "current-price";
     protected static final String SENTIMENT_ATTRIBUTE = "sentiment";
-    protected static final String REMARK_ATTRIBUTE = "remark";
-    protected static final String RETURN_ATTRIBUTE = "returns";
+    protected static final String REMARK_ATTRIBUTE = "remarks";
+    protected static final String RETURN_ATTRIBUTE = "past-returns";
     protected static final String ENTRY_PRICE_ATTRIBUTE = "entry-price";
     protected static final String EXIT_PRICE_ATTRIBUTE = "exit-price";
     protected static final String EXPIRY_ATTRIBUTE = "expiry";
+    protected static final String DONE_ATTRIBUTE = "undone";
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/EditInstrumentParser.java:24]:
```suggestion
    protected static final String DONE_ATTRIBUTE = "done-status";
```

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java [hunk 9]
```diff
@@ -77,9 +78,9 @@ public static void editReturnParameter(HashSet<String> parametersGiven) {
         }
         TextUi.displayEditReturn();
         String inputReturn = getUserInput(WORKSPACE);
-        if (!Validate.isValidPastReturn(inputReturn)) {
+        while (!Validate.isValidPastReturn(inputReturn)) {
             ErrorMessage.displayEditReturnError();
-            return;
+            inputReturn = getUserInput(WORKSPACE);
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/EditInstrumentParser.java:83]: Use a do while loop, like the add instrument parser

File: src/main/java/seedu/mtracker/model/Instrument.java [hunk 10]
```diff
@@ -77,6 +82,13 @@ public void editName(HashMap<String, String> editedParameters) {
         setName(editedParameters.get(NAME_ATTRIBUTE));
     }
 
+    public void editDoneStatus(HashMap<String, String> editedParameters) {
+        if (!editedParameters.containsKey(DONE_ATTRIBUTE)) {
+            return;
+        }
+        markAsNotDone();
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/model/Instrument.java:89]: This will change based on above comments

**Review by theodorekwok — COMMENTED** [review]
Good work just some comments.

File: src/main/java/seedu/mtracker/model/Instrument.java [hunk 11]
```diff
@@ -77,6 +83,17 @@ public void editName(HashMap<String, String> editedParameters) {
         setName(editedParameters.get(NAME_ATTRIBUTE));
     }
 
+    public void editDoneStatus(HashMap<String, String> editedParameters) {
+        if (!editedParameters.containsKey(DONE_ATTRIBUTE)) {
+            return;
+        }
+        if (editedParameters.get(DONE_ATTRIBUTE).equals(DONE_INDICATOR)) {
+            markAsDone();
+        } else {
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/model/Instrument.java:92]: can add an assert in the else block that editedParameters.get(DONE_ATTRIBUTE) equals "undone" only

File: src/main/java/seedu/mtracker/ui/TextUi.java [hunk 12]
```diff
@@ -42,6 +42,7 @@
     private static final String EDIT_ENTRY_MESSAGE = "Enter new Entry Price:";
     private static final String EDIT_EXIT_MESSAGE = "Enter new Exit Price:";
     private static final String EDIT_EXPIRY_MESSAGE = "Enter new Expiry (YYYY-MM-DD):";
+    private static final String EDIT_STATUS_MESSAGE = "Enter new Status:";
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/ui/TextUi.java:45]:
```suggestion
    private static final String EDIT_STATUS_MESSAGE = "Enter new Status (please enter either done or undone):";

```

File: src/main/java/seedu/mtracker/error/ErrorMessage.java [hunk 13]
```diff
@@ -71,32 +71,15 @@
     public static final String EMPTY_CURR_PRICE_IN_FILE_ERROR = "Oh no! Looks like the curr price entry in the file"
             + " is empty.";
 
+    public static final String EDIT_EMPTY_ERROR = "Edit parameters cannot be empty, aborting edit process.";
+    public static final String INVALID_EDIT_STATUS = "Sorry status must not be empty"
+            + "and either y/n for done or not done.";
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/error/ErrorMessage.java:76]:
```suggestion
            + "Enter either done or undone.";
```
y/n doesn't really make sense given that its query abt status

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java [hunk 14]
```diff
@@ -75,52 +72,60 @@ public static void editReturnParameter(HashSet<String> parametersGiven) {
...
+
+    public static void editDoneStatus(HashSet<String> parametersGiven) {
+        if (!parametersGiven.contains(DONE_ATTRIBUTE)) {
             return;
         }
-        editedParameters.put(EXPIRY_ATTRIBUTE, inputExpiry);
+        String inputStatus;
+        do {
+            TextUi.displayEditStatus();
+            inputStatus = getUserInput(WORKSPACE);
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/EditInstrumentParser.java:126]: make it to lowercase so that it is case insensitive since we only allow 2 values done and undone

File: src/main/java/seedu/mtracker/commons/Validate.java [hunk 15]
```diff
@@ -36,6 +37,8 @@
     public static final String POSITIVE_SENTIMENT = "positive";
     public static final String NEUTRAL_SENTIMENT = "neutral";
     public static final String NEGATIVE_SENTIMENT = "negative";
+    public static final String DONE_INDICATOR = "y";
+    public static final String NOT_DONE_INDICATOR = "n";
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/commons/Validate.java:41]:
```suggestion
    public static final String DONE_INDICATOR = "done";
    public static final String NOT_DONE_INDICATOR = "undone";
```

**Review by theodorekwok — COMMENTED** [review]
Just some minor remarks. Given the we are asking the user to enter a done status, it doesn't quite make sense to say y or n

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java [hunk 16]
```diff
@@ -118,7 +119,20 @@ public static void editExitPriceParameter(HashSet<String> parametersGiven)
...
-    public static void editExpiryParameter(HashSet<String> parametersGiven)
+    public void editDoneStatus(HashSet<String> parametersGiven) throws OperationAbortedError {
+        if (!parametersGiven.contains(DONE_ATTRIBUTE)) {
+            return;
+        }
+        String inputStatus;
+        do {
+            TextUi.displayEditStatus();
+            inputStatus = getUserInput(WORKSPACE).toLowerCase();
+            checkIfAbort(inputStatus, WORKSPACE);
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/EditInstrumentParser.java:130]: This is good, I apologise for not catching the rest earlier, but for the rest of editparameters method can shift the TextUi.displayEditXYZ() into the do while loop? Right now its just querying the edit parameter forever but the user don't see the instruction

File: src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java [hunk 17]
```diff
@@ -0,0 +1,123 @@
...
+    }
+
+    @Test
+    void editInstrumentParam_nameAndRemark_expectSuccess() throws OperationAbortedError {
+        testEditInstrumentParameters(USER_INPUT_EDIT_NAME_AND_REMARK,
+                PARAM_INPUT_NAME_AND_REMARK,
+                EXPECTED_KEYS_NAME_AND_REMARK,
+                EXPECTED_OUTPUT_NAME_AND_REMARK);
+    }
+
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java:78]: Remove gap here

File: src/main/java/seedu/mtracker/model/Instrument.java [hunk 18]
```diff
@@ -77,6 +84,18 @@ public void editName(HashMap<String, String> editedParameters) {
...
 
+    public void editDoneStatus(HashMap<String, String> editedParameters) {
+        if (!editedParameters.containsKey(DONE_ATTRIBUTE)) {
+            return;
+        }
+        if (editedParameters.get(DONE_ATTRIBUTE).equals(DONE_INDICATOR)) {
+            markAsDone();
+        } else {
+            assert (editedParameters.get(DONE_ATTRIBUTE).equals(UNDONE_INDICATOR));
+            markAsNotDone();
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/model/Instrument.java:95]: Actually can remove the else block here and in the if block just return after markAsDone()

File: src/main/java/seedu/mtracker/console/EditInstrumentParser.java (hunk 16 above)
Comment (theodorekwok) [reply src/main/java/seedu/mtracker/console/EditInstrumentParser.java:130]: Same for the do while loop in add instrument type. Currently TextUi.displayAddInstrumentFirstInstruction(); it is only displayed once. Can help shift it inside the do while loop

File: src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java [hunk 19]
```diff
@@ -20,7 +20,11 @@ public String execute() {
         String instrumentBefore = instrumentToEdit.getAllParams();
         instrumentManager.editInstrument(index, editedParameters);
         String instrumentAfter = instrumentToEdit.getAllParams();
-        TextUi.displayEditBeforeAfter(instrumentBefore, instrumentAfter);
+        if (instrumentBefore.equals(instrumentAfter)) {
+            TextUi.displayEditNoChange();
+        } else {
+            TextUi.displayEditBeforeAfter(instrumentBefore, instrumentAfter);
+        }
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java:27]: Can shift this conditional inside the TextUi.displayEditBeforeAfter

File: src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java [hunk 20]
```diff
@@ -0,0 +1,123 @@
...
+    public static final String TEST_NAME = "Test";
+    public static final double TEST_PRICE = 1.0;
+    public static final String TEST_SENTIMENT = "neutral";
+    public static final String TEST_REMARK = "";
+    public static final Instrument TEST_STOCK = new Stock(TEST_NAME, TEST_PRICE, TEST_SENTIMENT, TEST_REMARK);
+    public static final int TEST_INDEX = 0;
+
+    @Override
+    public int getParameterSize() {
+        return 0;
```
Comment (theodorekwok) [inline src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java:49]: Can abstract to return SIZE_ZERO

**Review by theodorekwok — COMMENTED** [review]
Good work, just some minor comments

**Review by theodorekwok — APPROVED** [review]
LGTM! Thanks!
