### PR TITLE
Handled invalid price inputs and empty expiry for forex

### LINKED ISSUE #43: Add some exceptions for forex classes
Make code more defensive through exceptions.

### PR DESCRIPTION
**Pull request by KVignesh122**
Fix #43

### CODE REVIEW

File: src/main/java/seedu/mtracker/console/AddForexParser.java [hunk 1]
```diff
@@ -33,17 +33,26 @@ public void addForexRemarksToParameter() {
     }
 
     public void addForexEntryToParameter() {
-        String entryPrice = getForexEntryFromUser();
+        String entryPrice;
+        do {
+            entryPrice = getForexEntryFromUser();
+        } while (!isValidPrice(entryPrice));
         parameters.add(entryPrice);
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/AddForexParser.java:40]: Nice, I think we shld do this way for the other parameters, will create new issue from this

File: src/main/java/seedu/mtracker/console/AddInstrumentParser.java [hunk 2]
```diff
@@ -61,12 +61,25 @@ public static boolean isValidPrice(String currentPrice) {
...
         }
         return isValid;
     }
 
+    public static boolean isExpiryFilled(String expiryInput) {
+        boolean isFilled = true;
+        try {
+            if (expiryInput.isEmpty() | expiryInput.isBlank()) {
+                throw new IllegalArgumentException();
+            }
```
Comment (theodorekwok) [inline src/main/java/seedu/mtracker/console/AddInstrumentParser.java:75]: I dont think the isBlank is needed cause the getUserCommand automatically trims whitespaces, so even if user puts in blank spaces the trimming will make it an empty string

Comment (KVignesh122) [reply src/main/java/seedu/mtracker/console/AddInstrumentParser.java:75]: Ok so I will remove the 2nd .isBlank() condition then.
